version: 2.1

parameters:
  run_test:
    type: boolean
    default: false

jobs:
  test:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Testing the build and deploy image
          command: |
            echo "Testing the build and deploy image using the role: $AWS_ROLE_ARN"

workflows:
  run-tests:
    when: << pipeline.parameters.run_test >>
    jobs:
      - test
